// docs/.vitepress/configs/hooks/OgImageTemplate.tsx
/** @jsx react-jsx **/

type OgImageTemplateProps = {
  title: string
  image: string
}

export function OgImageTemplate({ title, image }: OgImageTemplateProps) {
  return (
    <div tw='w-full h-full bg-black flex flex-col relative overflow-hidden font-[Inter]'>
      <img tw='absolute inset-0 w-full h-full object-cover' src={image} />
      <div tw='relative z-1 p-10 w-full min-h-0 grow flex flex-col items-center justify-between'>
        <div tw='w-full flex justify-between items-center text-5xl font-medium'>
          <div tw='flex items-center'>
            <div tw='text-zinc-100 ml-2 mt-1 font-semibold'>wotaku.wiki</div>
          </div>
          <img tw='h-12 w-16' src='https://i.wotaku.wiki/f/logo.svg' />
        </div>
        <div tw='w-full pr-56 flex flex-col items-start justify-end'>
          <div tw='text-[#f7f7f7] text-6xl font-bold'>{title}</div>
        </div>
      </div>
      <div tw='shrink-0 h-2 w-full flex' />
    </div>
  )
}

// .vitepress/theme/components/OgImageTemplate.vue
<script setup lang="ts">
defineProps<{ title: string; description?: string }>()
</script>

<template>
  <div
    tw="w-full h-full bg-black flex flex-col"
    style="background-image: url(https://i.ibb.co/9w9MYDf/og2-1.png)"
  >
    <div
      tw="p-10 w-full min-h-0 grow flex flex-col items-center justify-between"
    >
      <div tw="w-full flex justify-between items-center text-4xl font-medium">
        <div tw="flex items-center">
          <div tw="text-zinc-100 ml-2 mt-1 font-semibold">
            Wotaku.moe
          </div>
        </div>
      </div>
      <div tw="w-full pr-56 flex flex-col items-start justify-end">
        <div style="color: #f7f7f7" tw="text-6xl font-bold" v-html="title" />
      </div>
    </div>
    <div tw="shrink-0 h-2 w-full flex" style="background-color: #56b4fc" />
  </div>
</template>
